### ISSUE TITLE
Parts needed to monitor all this.

### ISSUE THREAD

**Issue by cob94440** [oncleben31/ha-pool_pump#12]
**Is your feature request related to a problem? Please describe.**
Maybe you can tell us which part you build

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by oncleben31** [comment]
I don't understand. Can you please review the content of your issue ? And detail your question or expectations.

**Comment by cob94440** [comment]
En fait j'aimerais connaître les éléments que tu as utilisés pour
automatiser la pompe. Actuellement j'ai un coffret électrique dédié avec
mode auto et allumage avec horloge enfin quand elle fonctionne. Et une
lampe.
Tu es parti sur du sonoff si j'ai suivi.

Bien cordialement
Christophe

**Comment by oncleben31** [comment]
I use a Sonoff pow R2. But the power measurement is useless in my case because I have implement it in paralel of the horloge after discussing with electricity experts in the community. This decision avoid having too much peak power going thru the Sonoff when starting the pump.

Horloge and SonOff pilot the contactor driving the pump . By default the Horloge is switched off (but can be reactivated as backup plan) and the Sonoff is piloted by Home Assistant.

It's not mandatory but I have flashed the sonoff firmware with [ESPhome](https://esphome.io/)
